# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/Documents/opengl-dominion

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/Documents/opengl-dominion

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Documents/opengl-dominion/CMakeFiles /home/alex/Documents/opengl-dominion//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Documents/opengl-dominion/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named DCLP

# Build rule for target.
DCLP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DCLP
.PHONY : DCLP

# fast build rule for target.
DCLP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/build
.PHONY : DCLP/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f glfw/CMakeFiles/uninstall.dir/build.make glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f glfw/src/CMakeFiles/update_mappings.dir/build.make glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f glfw/src/CMakeFiles/glfw.dir/build.make glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named clipboard

# Build rule for target.
clipboard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clipboard
.PHONY : clipboard

# fast build rule for target.
clipboard/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/clipboard.dir/build.make glfw/tests/CMakeFiles/clipboard.dir/build
.PHONY : clipboard/fast

#=============================================================================
# Target rules for targets named events

# Build rule for target.
events: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 events
.PHONY : events

# fast build rule for target.
events/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/events.dir/build.make glfw/tests/CMakeFiles/events.dir/build
.PHONY : events/fast

#=============================================================================
# Target rules for targets named msaa

# Build rule for target.
msaa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 msaa
.PHONY : msaa

# fast build rule for target.
msaa/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/msaa.dir/build.make glfw/tests/CMakeFiles/msaa.dir/build
.PHONY : msaa/fast

#=============================================================================
# Target rules for targets named glfwinfo

# Build rule for target.
glfwinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfwinfo
.PHONY : glfwinfo

# fast build rule for target.
glfwinfo/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/glfwinfo.dir/build.make glfw/tests/CMakeFiles/glfwinfo.dir/build
.PHONY : glfwinfo/fast

#=============================================================================
# Target rules for targets named iconify

# Build rule for target.
iconify: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iconify
.PHONY : iconify

# fast build rule for target.
iconify/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/iconify.dir/build.make glfw/tests/CMakeFiles/iconify.dir/build
.PHONY : iconify/fast

#=============================================================================
# Target rules for targets named monitors

# Build rule for target.
monitors: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 monitors
.PHONY : monitors

# fast build rule for target.
monitors/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/monitors.dir/build.make glfw/tests/CMakeFiles/monitors.dir/build
.PHONY : monitors/fast

#=============================================================================
# Target rules for targets named reopen

# Build rule for target.
reopen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reopen
.PHONY : reopen

# fast build rule for target.
reopen/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/reopen.dir/build.make glfw/tests/CMakeFiles/reopen.dir/build
.PHONY : reopen/fast

#=============================================================================
# Target rules for targets named cursor

# Build rule for target.
cursor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cursor
.PHONY : cursor

# fast build rule for target.
cursor/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/cursor.dir/build.make glfw/tests/CMakeFiles/cursor.dir/build
.PHONY : cursor/fast

#=============================================================================
# Target rules for targets named empty

# Build rule for target.
empty: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 empty
.PHONY : empty

# fast build rule for target.
empty/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/empty.dir/build.make glfw/tests/CMakeFiles/empty.dir/build
.PHONY : empty/fast

#=============================================================================
# Target rules for targets named gamma

# Build rule for target.
gamma: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gamma
.PHONY : gamma

# fast build rule for target.
gamma/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/gamma.dir/build.make glfw/tests/CMakeFiles/gamma.dir/build
.PHONY : gamma/fast

#=============================================================================
# Target rules for targets named icon

# Build rule for target.
icon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 icon
.PHONY : icon

# fast build rule for target.
icon/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/icon.dir/build.make glfw/tests/CMakeFiles/icon.dir/build
.PHONY : icon/fast

#=============================================================================
# Target rules for targets named inputlag

# Build rule for target.
inputlag: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 inputlag
.PHONY : inputlag

# fast build rule for target.
inputlag/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/inputlag.dir/build.make glfw/tests/CMakeFiles/inputlag.dir/build
.PHONY : inputlag/fast

#=============================================================================
# Target rules for targets named joysticks

# Build rule for target.
joysticks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 joysticks
.PHONY : joysticks

# fast build rule for target.
joysticks/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/joysticks.dir/build.make glfw/tests/CMakeFiles/joysticks.dir/build
.PHONY : joysticks/fast

#=============================================================================
# Target rules for targets named opacity

# Build rule for target.
opacity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opacity
.PHONY : opacity

# fast build rule for target.
opacity/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/opacity.dir/build.make glfw/tests/CMakeFiles/opacity.dir/build
.PHONY : opacity/fast

#=============================================================================
# Target rules for targets named tearing

# Build rule for target.
tearing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tearing
.PHONY : tearing

# fast build rule for target.
tearing/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/tearing.dir/build.make glfw/tests/CMakeFiles/tearing.dir/build
.PHONY : tearing/fast

#=============================================================================
# Target rules for targets named threads

# Build rule for target.
threads: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 threads
.PHONY : threads

# fast build rule for target.
threads/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/threads.dir/build.make glfw/tests/CMakeFiles/threads.dir/build
.PHONY : threads/fast

#=============================================================================
# Target rules for targets named timeout

# Build rule for target.
timeout: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timeout
.PHONY : timeout

# fast build rule for target.
timeout/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/timeout.dir/build.make glfw/tests/CMakeFiles/timeout.dir/build
.PHONY : timeout/fast

#=============================================================================
# Target rules for targets named title

# Build rule for target.
title: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 title
.PHONY : title

# fast build rule for target.
title/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/title.dir/build.make glfw/tests/CMakeFiles/title.dir/build
.PHONY : title/fast

#=============================================================================
# Target rules for targets named triangle-vulkan

# Build rule for target.
triangle-vulkan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangle-vulkan
.PHONY : triangle-vulkan

# fast build rule for target.
triangle-vulkan/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/triangle-vulkan.dir/build.make glfw/tests/CMakeFiles/triangle-vulkan.dir/build
.PHONY : triangle-vulkan/fast

#=============================================================================
# Target rules for targets named windows

# Build rule for target.
windows: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 windows
.PHONY : windows

# fast build rule for target.
windows/fast:
	$(MAKE) $(MAKESILENT) -f glfw/tests/CMakeFiles/windows.dir/build.make glfw/tests/CMakeFiles/windows.dir/build
.PHONY : windows/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) $(MAKESILENT) -f glfw/docs/CMakeFiles/docs.dir/build.make glfw/docs/CMakeFiles/docs.dir/build
.PHONY : docs/fast

imgui/backends/imgui_impl_glfw.o: imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui/backends/imgui_impl_glfw.o

# target to build an object file
imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui/backends/imgui_impl_glfw.cpp.o

imgui/backends/imgui_impl_glfw.i: imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui/backends/imgui_impl_glfw.cpp.i

imgui/backends/imgui_impl_glfw.s: imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui/backends/imgui_impl_glfw.cpp.s

imgui/backends/imgui_impl_opengl3.o: imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl3.o

# target to build an object file
imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.o

imgui/backends/imgui_impl_opengl3.i: imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.i

imgui/backends/imgui_impl_opengl3.s: imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.s

imgui/imgui.o: imgui/imgui.cpp.o
.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_demo.o: imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.o

# target to build an object file
imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.cpp.o

imgui/imgui_demo.i: imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.i

# target to preprocess a source file
imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.cpp.i

imgui/imgui_demo.s: imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.s

# target to generate assembly for a file
imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_tables.o: imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.o

# target to build an object file
imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.cpp.o

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

include/glad/glad.o: include/glad/glad.c.o
.PHONY : include/glad/glad.o

# target to build an object file
include/glad/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/include/glad/glad.c.o
.PHONY : include/glad/glad.c.o

include/glad/glad.i: include/glad/glad.c.i
.PHONY : include/glad/glad.i

# target to preprocess a source file
include/glad/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/include/glad/glad.c.i
.PHONY : include/glad/glad.c.i

include/glad/glad.s: include/glad/glad.c.s
.PHONY : include/glad/glad.s

# target to generate assembly for a file
include/glad/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/include/glad/glad.c.s
.PHONY : include/glad/glad.c.s

include/stb_image.o: include/stb_image.cpp.o
.PHONY : include/stb_image.o

# target to build an object file
include/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/include/stb_image.cpp.o
.PHONY : include/stb_image.cpp.o

include/stb_image.i: include/stb_image.cpp.i
.PHONY : include/stb_image.i

# target to preprocess a source file
include/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/include/stb_image.cpp.i
.PHONY : include/stb_image.cpp.i

include/stb_image.s: include/stb_image.cpp.s
.PHONY : include/stb_image.s

# target to generate assembly for a file
include/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/include/stb_image.cpp.s
.PHONY : include/stb_image.cpp.s

src/Image.o: src/Image.cpp.o
.PHONY : src/Image.o

# target to build an object file
src/Image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Image.cpp.o
.PHONY : src/Image.cpp.o

src/Image.i: src/Image.cpp.i
.PHONY : src/Image.i

# target to preprocess a source file
src/Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Image.cpp.i
.PHONY : src/Image.cpp.i

src/Image.s: src/Image.cpp.s
.PHONY : src/Image.s

# target to generate assembly for a file
src/Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Image.cpp.s
.PHONY : src/Image.cpp.s

src/Log.o: src/Log.cpp.o
.PHONY : src/Log.o

# target to build an object file
src/Log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Log.cpp.o
.PHONY : src/Log.cpp.o

src/Log.i: src/Log.cpp.i
.PHONY : src/Log.i

# target to preprocess a source file
src/Log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Log.cpp.i
.PHONY : src/Log.cpp.i

src/Log.s: src/Log.cpp.s
.PHONY : src/Log.s

# target to generate assembly for a file
src/Log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Log.cpp.s
.PHONY : src/Log.cpp.s

src/OSspecifics.o: src/OSspecifics.cpp.o
.PHONY : src/OSspecifics.o

# target to build an object file
src/OSspecifics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/OSspecifics.cpp.o
.PHONY : src/OSspecifics.cpp.o

src/OSspecifics.i: src/OSspecifics.cpp.i
.PHONY : src/OSspecifics.i

# target to preprocess a source file
src/OSspecifics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/OSspecifics.cpp.i
.PHONY : src/OSspecifics.cpp.i

src/OSspecifics.s: src/OSspecifics.cpp.s
.PHONY : src/OSspecifics.s

# target to generate assembly for a file
src/OSspecifics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/OSspecifics.cpp.s
.PHONY : src/OSspecifics.cpp.s

src/Resources.o: src/Resources.cpp.o
.PHONY : src/Resources.o

# target to build an object file
src/Resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Resources.cpp.o
.PHONY : src/Resources.cpp.o

src/Resources.i: src/Resources.cpp.i
.PHONY : src/Resources.i

# target to preprocess a source file
src/Resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Resources.cpp.i
.PHONY : src/Resources.cpp.i

src/Resources.s: src/Resources.cpp.s
.PHONY : src/Resources.s

# target to generate assembly for a file
src/Resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Resources.cpp.s
.PHONY : src/Resources.cpp.s

src/Saves.o: src/Saves.cpp.o
.PHONY : src/Saves.o

# target to build an object file
src/Saves.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Saves.cpp.o
.PHONY : src/Saves.cpp.o

src/Saves.i: src/Saves.cpp.i
.PHONY : src/Saves.i

# target to preprocess a source file
src/Saves.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Saves.cpp.i
.PHONY : src/Saves.cpp.i

src/Saves.s: src/Saves.cpp.s
.PHONY : src/Saves.s

# target to generate assembly for a file
src/Saves.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Saves.cpp.s
.PHONY : src/Saves.cpp.s

src/States.o: src/States.cpp.o
.PHONY : src/States.o

# target to build an object file
src/States.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/States.cpp.o
.PHONY : src/States.cpp.o

src/States.i: src/States.cpp.i
.PHONY : src/States.i

# target to preprocess a source file
src/States.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/States.cpp.i
.PHONY : src/States.cpp.i

src/States.s: src/States.cpp.s
.PHONY : src/States.s

# target to generate assembly for a file
src/States.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/States.cpp.s
.PHONY : src/States.cpp.s

src/Text.o: src/Text.cpp.o
.PHONY : src/Text.o

# target to build an object file
src/Text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Text.cpp.o
.PHONY : src/Text.cpp.o

src/Text.i: src/Text.cpp.i
.PHONY : src/Text.i

# target to preprocess a source file
src/Text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Text.cpp.i
.PHONY : src/Text.cpp.i

src/Text.s: src/Text.cpp.s
.PHONY : src/Text.s

# target to generate assembly for a file
src/Text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/Text.cpp.s
.PHONY : src/Text.cpp.s

src/handler.o: src/handler.cpp.o
.PHONY : src/handler.o

# target to build an object file
src/handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/handler.cpp.o
.PHONY : src/handler.cpp.o

src/handler.i: src/handler.cpp.i
.PHONY : src/handler.i

# target to preprocess a source file
src/handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/handler.cpp.i
.PHONY : src/handler.cpp.i

src/handler.s: src/handler.cpp.s
.PHONY : src/handler.s

# target to generate assembly for a file
src/handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/handler.cpp.s
.PHONY : src/handler.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DCLP.dir/build.make CMakeFiles/DCLP.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... docs"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... DCLP"
	@echo "... clipboard"
	@echo "... cursor"
	@echo "... empty"
	@echo "... events"
	@echo "... gamma"
	@echo "... glfw"
	@echo "... glfwinfo"
	@echo "... icon"
	@echo "... iconify"
	@echo "... imgui"
	@echo "... inputlag"
	@echo "... joysticks"
	@echo "... monitors"
	@echo "... msaa"
	@echo "... opacity"
	@echo "... reopen"
	@echo "... tearing"
	@echo "... threads"
	@echo "... timeout"
	@echo "... title"
	@echo "... triangle-vulkan"
	@echo "... windows"
	@echo "... imgui/backends/imgui_impl_glfw.o"
	@echo "... imgui/backends/imgui_impl_glfw.i"
	@echo "... imgui/backends/imgui_impl_glfw.s"
	@echo "... imgui/backends/imgui_impl_opengl3.o"
	@echo "... imgui/backends/imgui_impl_opengl3.i"
	@echo "... imgui/backends/imgui_impl_opengl3.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_demo.o"
	@echo "... imgui/imgui_demo.i"
	@echo "... imgui/imgui_demo.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_tables.o"
	@echo "... imgui/imgui_tables.i"
	@echo "... imgui/imgui_tables.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... include/glad/glad.o"
	@echo "... include/glad/glad.i"
	@echo "... include/glad/glad.s"
	@echo "... include/stb_image.o"
	@echo "... include/stb_image.i"
	@echo "... include/stb_image.s"
	@echo "... src/Image.o"
	@echo "... src/Image.i"
	@echo "... src/Image.s"
	@echo "... src/Log.o"
	@echo "... src/Log.i"
	@echo "... src/Log.s"
	@echo "... src/OSspecifics.o"
	@echo "... src/OSspecifics.i"
	@echo "... src/OSspecifics.s"
	@echo "... src/Resources.o"
	@echo "... src/Resources.i"
	@echo "... src/Resources.s"
	@echo "... src/Saves.o"
	@echo "... src/Saves.i"
	@echo "... src/Saves.s"
	@echo "... src/States.o"
	@echo "... src/States.i"
	@echo "... src/States.s"
	@echo "... src/Text.o"
	@echo "... src/Text.i"
	@echo "... src/Text.s"
	@echo "... src/handler.o"
	@echo "... src/handler.i"
	@echo "... src/handler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

